#! /bin/bash

export VERSION="48"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export PACKAGES="\
    chimera \
    chimeraos-dracut-cfg \
    chimeraos-fake-mkinitcpio \
    chimeraos-device-quirks-git \
    plymouth-theme-chimeraos \
"

PACKAGES+="\
    accountsservice \
    acpi_call-dkms \
    alsa-firmware \
    alsa-utils \
    amd-ucode \
    asusctl \
    ayaneo-platform-dkms-git \
    ayn-platform-dkms-git \
    bash-completion \
    bcm20702a1-firmware \
    boxtron \
    broadcom-wl-dkms \
    bzip2 \
    cifs-utils \
    cpupower \
    diffutils \
    distrobox \
    dkms \
    dmidecode \
    dosbox \
    downgrade \
    dracut \
    efibootmgr \
    epiphany \
    ethtool \
    evdev-keepalive \
    evtest \
    fakeroot \
    ffmpeg \
    ffmpegthumbnailer \
    file \
    firejail \
    flatpak \
    fmt \
    frzr-git \
    fuse2\
    fuse-zip \
    fwupd \
    gamescope-session-steam-git \
    gamescope-session-steam-plus-git \
    git \
    gnome-browser-connector \
    gnome-console \
    gnome-control-center \
    gnome-disk-utility \
    gnome-keyring \
    gnome-menus \
    gnome-session \
    gnome-shell \
    gnome-software \
    gnome-system-monitor \
    gnome-text-editor \
    gnome-tweaks \
    gst-plugin-pipewire \
    gvfs-nfs \
    gvfs-smb \
    gzip \
    haveged \
    hhfc-git \
    htop \
    inputplumber-bin \
    intel-gpu-tools \
    intel-media-driver \
    intel-ucode \
    intel-undervolt \
    kanit-font \
    legendary \
    less \
    lib32-curl \
    lib32-fontconfig \
    lib32-freetype2\
    lib32-libgpg-error \
    lib32-libnm \
    lib32-libva \
    lib32-libva-intel-driver \
    lib32-libva-vdpau-driver \
    lib32-libxcrypt-compat \
    lib32-libxinerama \
    lib32-mangohud \
    lib32-openal \
    lib32-pipewire \
    lib32-sdl2\
    lib32-systemd \
    lib32-vulkan-icd-loader \
    libcurl-gnutls \
    libidn11 \
    libretro-beetle-pce-fast \
    libretro-beetle-psx-hw \
    libretro-citra \
    libretro-desmume \
    libretro-dolphin \
    libretro-dosbox-pure-git \
    libretro-flycast \
    libretro-genesis-plus-gx \
    libretro-kronos \
    libretro-mesen-s \
    libretro-mgba \
    libretro-mupen64plus-next \
    libretro-nestopia \
    libretro-opera-git \
    libretro-picodrive \
    libretro-ppsspp \
    libretro-prosystem-git \
    libretro-shaders-slang \
    libretro-snes9x \
    libretro-stella2014-git \
    libretro-virtualjaguar-git \
    libva-intel-driver \
    libva-vdpau-driver \
    libxcrypt-compat \
    libxss \
    lightdm \
    liquidctl \
    logrotate \
    loupe \
    lrzip \
    lshw \
    mangohud \
    mesa-demos \
    modemmanager \
    nano \
    nautilus \
    networkmanager \
    nfs-utils \
    nintendo-udev \
    noto-fonts-emoji \
    nss-mdns \
    openal \
    opengamepadui-bin \
    opengamepadui-session-git \
    openrazer-daemon \
    openssh \
    p7zip \
    pikaur \
    pipewire \
    pipewire-alsa \
    pipewire-jack \
    pipewire-pulse \
    plymouth \
    podman \
    powerstation-bin \
    pulsemixer \
    python \
    python-gbopyrator \
    python-notify2\
    python-vdf \
    qtractor \
    retroarch \
    rsync \
    rtl8812au-dkms-git \
    rtl8814au-dkms-git \
    rtl8821au-dkms-git \
    ryzenadj-git \
    smbclient \
    sof-firmware \
    sshfs \
    steam \
    steam_notif_daemon \
    steam-powerbuttond-git \
    steam-removable-media-git \
    sudo \
    tar \
    tree \
    ttf-liberation \
    unace \
    unrar \
    unzip \
    usb_modeswitch \
    usbutils \
    vim \
    vulkan-icd-loader \
    wavpack \
    wget \
    which \
    wireplumber \
    wqy-zenhei \
    wyvern \
    xdg-desktop-portal \
    xdg-desktop-portal-gnome \
    xdg-desktop-portal-wlr \
    xdg-user-dirs-gtk \
    xf86-video-amdgpu \
    xonedo-dkms \
    xonedo-firmware \
    xorg-server \
    xz \
    zenergy-dkms-git \
    zip \
"

export PACKAGE_OVERRIDES="\
    https://archive.archlinux.org/repos/2023/06/28/extra/os/x86_64/libretro-pcsx2-11900-2-x86_64.pkg.tar.zst \
    https://archive.archlinux.org/packages/l/libretro-mame/libretro-mame-85763-1-x86_64.pkg.tar.zst \
"

export SERVICES="\
    NetworkManager \
    avahi-daemon \
    bluetooth \
    bluetooth-workaround \
    fstrim.timer \
    haveged \
    home-swapfile.swap \
    inputplumber \
    lightdm \
    powerstation \
    steam-powerbuttond \
    sshd \
    systemd-timesyncd \
    swapfile \
"

export USER_SERVICES="\
    chimera.service \
    pipewire \
    steam-patch.service \
    chimera-cart-monitor.service \
"

export FILES_TO_DELETE="\
    /boot/initramfs-linux-fallback.img \
    /usr/share/SFML \
    /usr/share/doc \
    /usr/share/gtk-doc \
    /usr/share/help \
    /usr/share/man \
"

if [[ ${1} == *"git" ]]; then
    PACKAGES+=" \
        lib32-mesa-git \
        mesa-git \
        linux-firmware-git \
        gamescope-plus \
    "
elif [[ ${1} == *"nvidia" ]]; then
    PACKAGES+=" \
        chos/mesa-vdpau \
        gamescope-plus \
        lib32-nvidia-utils \
        lib32-opencl-nvidia \
        nvidia-dkms \
        nvidia-prime \
        nvidia-utils \
        opencl-nvidia \
        linux-firmware \
        linux-firmware-valve \
    "
    SERVICES+=" \
        nvidia-powerd \
        "
else
    PACKAGES+=" \
        chos/lib32-libva-mesa-driver-chimeraos \
        chos/lib32-mesa-chimeraos \
        chos/lib32-mesa-vdpau-chimeraos \
        chos/lib32-opencl-rusticl-mesa-chimeraos \
        chos/lib32-vulkan-intel-chimeraos \
        chos/lib32-vulkan-mesa-layers-chimeraos \
        chos/lib32-vulkan-radeon-chimeraos \
        chos/lib32-vulkan-nouveau-chimeraos \
        chos/lib32-vulkan-swrast-chimeraos \
        chos/libva-mesa-driver-chimeraos \
        chos/mesa-chimeraos \
        chos/opencl-rusticl-mesa-chimeraos \
        chos/vulkan-intel-chimeraos \
        chos/vulkan-mesa-layers-chimeraos \
        chos/vulkan-radeon-chimeraos \
        chos/vulkan-nouveau-chimeraos \
        chos/vulkan-swrast-chimeraos \
        gamescope-plus \
        linux-firmware \
        linux-firmware-valve \
    " 
fi
postinstallhook() {
    # Add sudo permissions
    sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
    echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
    " >/etc/sudoers.d/steam
    echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
    ${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
    ${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
    " >/etc/sudoers.d/chimera

    # download and add racing wheel udev rules
    pushd /usr/lib/udev/rules.d
    curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
    curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
    curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
    popd

    # Remove build tools for slimmer image
    rm /usr/share/libalpm/hooks/70-dkms-install.hook
    rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
    rm /usr/share/libalpm/hooks/71-dkms-remove.hook
    pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

    # remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
    rm /usr/bin/dolphin-emu
    rm /usr/bin/dolphin-emu-nogui
    # dolphin-tool is no longer created in new builds?
    #rm /usr/bin/dolphin-tool
    rm /usr/share/applications/dolphin-emu.desktop

    # clean up desktop shortcuts
    sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop
    find /usr/share/applications/* |
    grep -v org.chimeraos.Gamescope.desktop |
    grep -v org.chimeraos.app.desktop |
    grep -v org.gnome.Console.desktop |
    grep -v org.gnome.DiskUtility.desktop |
    grep -v org.gnome.FileRoller.desktop |
    grep -v org.gnome.Nautilus.desktop |
    grep -v org.gnome.Settings.desktop |
    grep -v org.gnome.Software.desktop |
    grep -v org.gnome.TextEditor.desktop |
    grep -v steam.desktop |
    xargs -I {} sh -c "echo NoDisplay=true >> {}"

    # force -steamdeck option in desktop mode to prevent constant steam updates
    sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

    # set permissions for intel_gpu_top and mangohud
    setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
}