name: Build packages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
env:
 IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
 BUILDER_TAG: ghcr.io/boukehaarsma23/chimeraos-builder:main
 IMAGE_NAME: chimeraos-oci

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:     
  build:
    if: github.event_name != 'pull_request'
    name: Build System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from manifest
        id: version
        run: |
          source ./manifest
          echo "SYSTEM_NAME=`echo ${SYSTEM_NAME}`" >> "$GITHUB_OUTPUT"
          echo "VERSION=`echo ${VERSION}`" >> "$GITHUB_OUTPUT"
          echo "SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> "$GITHUB_OUTPUT"
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7
      - name: Create empty system using chimeraos-builder
        run: |
          docker run --privileged -v $(pwd)/mnt:/mnt -v $(pwd):/workdir ${{ env.BUILDER_TAG }} /bin/bash /workdir/base.sh
      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # Build image using Buildah
      - name: Build Image
        id: build_image
        run: |
          sudo buildah bud -f ./Containerfile --label org.opencontainers.image.title=${{ env.IMAGE_NAME }} --label frzr.image.version="${{ steps.version.outputs.SYSTEM_NAME }}-${{ steps.version.outputs.VERSION }}_${{ steps.version.outputs.SHA }}" --build-arg SHA="${{ steps.version.outputs.SHA }}" -t ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }} .

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        run: |
          sudo buildah push --creds=${{ env.REGISTRY_USER }}:${{ env.REGISTRY_PASSWORD }} ${{ env.IMAGE_NAME }} ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}